# Generated by Django 4.0 on 2022-02-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='active',
        ),
    ]
