# Generated by Django 4.0 on 2022-02-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validaciones', '0002_remove_cost_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profitability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_purchase_range', models.IntegerField()),
                ('max_purchase_range', models.IntegerField()),
                ('typeA', models.IntegerField()),
                ('typeB', models.IntegerField()),
                ('typeC', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cost',
            name='vat',
        ),
        migrations.AddField(
            model_name='cost',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
