# Generated by Django 4.0 on 2022-02-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validaciones', '0004_cost_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='costs',
            field=models.ManyToManyField(blank=True, null=True, to='validaciones.CostQuantity'),
        ),
    ]
