# Generated by Django 4.0 on 2022-02-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validaciones', '0005_alter_validation_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='risk',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2')], null=True),
        ),
    ]
