# Generated by Django 4.0 on 2022-03-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validaciones', '0006_alter_validation_risk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costquantity',
            name='amount',
        ),
    ]
