# Generated by Django 4.0 on 2022-03-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validaciones', '0007_remove_costquantity_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='costquantity',
            name='amount',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
