# Generated by Django 3.2.13 on 2022-05-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validaciones', '0009_remove_cost_created_at_remove_cost_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
